import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("exports the complete portfolio as one continuous accessible page", async () => {
  const html = await readFile(new URL("../out/index.html", import.meta.url), "utf8");

  assert.match(html, /Marcus Leung \| Urban Studies Portfolio/i);
  assert.match(html, /geomatics, cartography and all about cities/i);
  assert.match(html, /hero-marcus\.png/i);
  assert.match(html, /How I see, read and shape the city/i);
  assert.match(html, /Bedford Court/i);
  assert.match(html, /Project [^A-Za-z0-9]W[^A-Za-z0-9]/i);
  assert.match(html, /RiVITALISE/i);
  assert.match(html, /portfolio-page-04\.jpg/i);
  assert.match(html, /portfolio-page-17\.jpg/i);
  assert.match(html, /class="portfolio-image-trigger"/i);
  assert.match(html, /class="portfolio-lightbox"/i);
  assert.match(html, /Left click to zoom in/i);
  assert.match(html, /draggable="false"/i);
  assert.doesNotMatch(html, /target="_blank"|<a[^>]+href="projects\/pages\/portfolio-page-/i);
  assert.match(html, /Research Assistant Intern/i);
  assert.doesNotMatch(html, /Research Assistant(?! Intern)/i);
  assert.doesNotMatch(html, /Summer Research Assistant Intern/i);
  assert.match(html, /Research Trainee/i);
  assert.match(html, /Docent Trainee/i);
  assert.match(html, /Very Hong Kong[\s\S]*Liber Research Community[\s\S]*The Conservancy Association Centre for Heritage/i);
  assert.match(html, /Jul 2026 - Present/i);
  assert.match(html, /2025-2026<br\/>Smart Design for a Resilient &amp; Cultural Southern Shore/i);
  assert.match(html, /Hong Kong Press Photographers Association Competition 2024/i);
  assert.match(html, /Merit Award — Tertiary Group/i);
  assert.doesNotMatch(html, /Finalist — Tertiary Group/i);
  assert.match(html, /1st Runner-up \(Student Feature\), Merit \(Student Photo Essay\)/i);
  assert.match(html, /Adobe Graphic Designer[\s\S]*Hong Kong Press Photographers Association Competition 2024[\s\S]*Integrated Photoshop Masterclass/i);
  assert.match(html, /Adobe Creative Suite \/ ArcGIS Pro \/ AutoCAD \/ Codex \/ D5 Render \/ Enscape \/ Figma \/ Microsoft Office \/ QGIS \/ Rhino \/ SketchUp \/ Twinmotion/i);
  assert.doesNotMatch(html, /Opencode/i);
  assert.match(html, /lytmarcus@link\.cuhk\.edu\.hk/i);
  assert.match(html, /href="#about"/i);
  assert.match(html, /href="#work"/i);
  assert.match(html, /href="#cv"/i);
  assert.match(html, /href="#contact"/i);
  assert.doesNotMatch(html, /Marcus_Leung_Yin_To_CV\.pdf/i);
  assert.doesNotMatch(html, /Leung_YinTo_Portfolio\.pdf/i);
  assert.match(html, /aria-label="Main navigation"/i);
  assert.doesNotMatch(html, /class="wordmark"|aria-label="Back to top"/i);
  assert.doesNotMatch(html, /Your site is taking shape|react-loading-skeleton/i);
});
